### ISSUE TITLE
Have a !value command (exemple) 

### ISSUE THREAD

**Issue by Sacuul** [enzo-billis/ZBot-TwitchChatBot-BTC#1]
Get a command to show the bitcoin value in realtime

**Comment by Sacuul** [comment]
fock this is not an issue sorry x)

**Comment by enzo-billis** [comment]
Hi Sacuul !
That a good idea, I will add it to my todo list 👍  Sorry for late reply...

**Comment by enzo-billis** [comment]
Hello @Sacuul,
This feature is actually done. It will be released soon 🎉 ! Stay tuned. 
Enzo
